"""Contrast-controlled color palettes for scientific Python."""

from .accessibility import (
    DEFAULT_ACCESSIBILITY_MODES,
    figure_to_rgba,
    figure_variants,
    simulate_cvd_image,
    simulate_figure,
    show_accessibility_panel,
    save_accessibility_panel,
    to_grayscale_image,
    to_print_stress_image,
)
from .alpha import AlphaCompensation, compensate_alpha, composite, minimum_alpha
from .api import (
    DEFAULT_LINESTYLES,
    DEFAULT_MARKERS,
    color_palette,
    contrast_palette,
    plot_scheme,
    scatter_scheme,
    show_palette,
)
from .color_spaces import contrast_ratio, delta_e_ok, relative_luminance, srgb_to_oklab, to_hex, to_rgb
from .contrast import luminance_contrast, luminance_ladder
from .presets import PalettePreset, register_palette, get_palette, available_palettes
from .publication import (
    TEX_PT_PER_INCH,
    LatexLayout,
    LatexProbeError,
    LatexFontInfo,
    find_latex_font,
    FigureAudit,
    FitResult,
    PublicationStyle,
    inspect_latex,
    latex_style,
    audit_figure,
    fit_figure_to_latex,
    verify_latex_placement,
)
from .contrast import print_safe_luminances
from .style import (
    HERI_CMAP,
    HERI_IRIDESCENT_HEX,
    HERI_NEUTRAL,
    HERI_PALETTE,
    available_styles,
    panel_label,
    save_figure,
    set_style,
    style_context,
)
from .palette import (
    ColorCell,
    ContrastGrid,
    Palette,
    RenderedColor,
    color_for_luminance,
    contrast_grid,
)

__all__ = [
    "TEX_PT_PER_INCH",
    "LatexLayout",
    "LatexProbeError",
    "LatexFontInfo",
    "find_latex_font",
    "FigureAudit",
    "FitResult",
    "PublicationStyle",
    "inspect_latex",
    "latex_style",
    "audit_figure",
    "fit_figure_to_latex",
    "verify_latex_placement",
    "AlphaCompensation",
    "HERI_CMAP",
    "HERI_IRIDESCENT_HEX",
    "HERI_NEUTRAL",
    "HERI_PALETTE",
    "ColorCell",
    "DEFAULT_LINESTYLES",
    "DEFAULT_MARKERS",
    "ContrastGrid",
    "Palette",
    "PalettePreset",
    "register_palette",
    "get_palette",
    "available_palettes",
    "RenderedColor",
    "color_for_luminance",
    "color_palette",
    "compensate_alpha",
    "composite",
    "contrast_grid",
    "contrast_ratio",
    "delta_e_ok",
    "luminance_contrast",
    "luminance_ladder",
    "minimum_alpha",
    "contrast_palette",
    "relative_luminance",
    "srgb_to_oklab",
    "show_palette",
    "available_styles",
    "panel_label",
    "plot_scheme",
    "print_safe_luminances",
    "scatter_scheme",
    "DEFAULT_ACCESSIBILITY_MODES",
    "figure_to_rgba",
    "figure_variants",
    "simulate_cvd_image",
    "simulate_figure",
    "show_accessibility_panel",
    "save_accessibility_panel",
    "to_grayscale_image",
    "to_print_stress_image",
    "save_figure",
    "set_style",
    "style_context",
    "to_hex",
    "to_rgb",
]

__version__ = "0.1.0"
